package be.brianvannimmen.petnest.ui.theme
import androidx.compose.ui.graphics.Color

// ── Licht thema ──────────────────────────────────────────────────────────────
val primaryLight = Color(0xFF86521A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCBF)
val onPrimaryContainerLight = Color(0xFF6A3B02)
val secondaryLight = Color(0xFF86521A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDCBF)
val onSecondaryContainerLight = Color(0xFF6A3B02)
val tertiaryLight = Color(0xFF79590C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDEA4)
val onTertiaryContainerLight = Color(0xFF5D4200)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF221A14)
val surfaceLight = Color(0xFFFFF8F1)
val onSurfaceLight = Color(0xFF1F1B13)
val surfaceVariantLight = Color(0xFFE9E2D0)
val onSurfaceVariantLight = Color(0xFF4A4739)
val outlineLight = Color(0xFF7B7768)
val outlineVariantLight = Color(0xFFCCC6B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF343027)
val inverseOnSurfaceLight = Color(0xFFF8F0E2)
val inversePrimaryLight = Color(0xFFFEB876)
val surfaceDimLight = Color(0xFFE1D9CC)
val surfaceBrightLight = Color(0xFFFFF8F1)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFBF3E5)
val surfaceContainerLight = Color(0xFFF5EDDF)
val surfaceContainerHighLight = Color(0xFFF0E7D9)
val surfaceContainerHighestLight = Color(0xFFEAE1D4)

// ── Donker thema ──────────────────────────────────────────────────────────────
val primaryDark = Color(0xFFFEB876)
val onPrimaryDark = Color(0xFF4B2800)
val primaryContainerDark = Color(0xFF6A3B02)
val onPrimaryContainerDark = Color(0xFFFFDCBF)
val secondaryDark = Color(0xFFFEB876)
val onSecondaryDark = Color(0xFF4B2800)
val secondaryContainerDark = Color(0xFF6A3B02)
val onSecondaryContainerDark = Color(0xFFFFDCBF)
val tertiaryDark = Color(0xFFECC06C)
val onTertiaryDark = Color(0xFF412D00)
val tertiaryContainerDark = Color(0xFF5D4200)
val onTertiaryContainerDark = Color(0xFFFFDEA4)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF19120C)
val onBackgroundDark = Color(0xFFEFE0D5)
val surfaceDark = Color(0xFF16130B)
val onSurfaceDark = Color(0xFFEAE1D4)
val surfaceVariantDark = Color(0xFF4A4739)
val onSurfaceVariantDark = Color(0xFFCCC6B5)
val outlineDark = Color(0xFF959180)
val outlineVariantDark = Color(0xFF4A4739)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAE1D4)
val inverseOnSurfaceDark = Color(0xFF343027)
val inversePrimaryDark = Color(0xFF86521A)
val surfaceDimDark = Color(0xFF16130B)
val surfaceBrightDark = Color(0xFF3D392F)
val surfaceContainerLowestDark = Color(0xFF110E07)
val surfaceContainerLowDark = Color(0xFF1F1B13)
val surfaceContainerDark = Color(0xFF231F17)
val surfaceContainerHighDark = Color(0xFF2D2A21)
val surfaceContainerHighestDark = Color(0xFF39342B)

// ── Extended: TopBar ──────────────────────────────────────────────────────────
val topBarLight = Color(0xFFF6EFE6)      // BeigeBackground
val onTopBarLight = Color(0xFF86521A)    // bruin (primary)
val topBarContainerLight = Color(0xFFF6EFE6)
val onTopBarContainerLight = Color(0xFF86521A)

val topBarDark = Color(0xFF19120C)       // donkere achtergrond
val onTopBarDark = Color(0xFFFEB876)     // licht tan (primary donker)
val topBarContainerDark = Color(0xFF19120C)
val onTopBarContainerDark = Color(0xFFFEB876)

// ── Custom ────────────────────────────────────────────────────────────────────
val BeigeBackground = Color(0xFFF6EFE6)
